# Generated by Django 2.2.1 on 2019-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vizpoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UtilityName', models.TextField(db_column='UtilityName')),
                ('StateName', models.TextField(db_column='StateName')),
                ('CountyName', models.TextField(db_column='CountyName')),
                ('OutageCount', models.IntegerField(blank=True, db_column='OutageCount', null=True)),
                ('CustomerCount', models.IntegerField(blank=True, db_column='CustomerCount', null=True)),
                ('RecordDateTime', models.DateTimeField(db_column='RecordDateTime')),
                ('StepCount', models.IntegerField(blank=True, db_column='StepCount', null=True)),
                ('PerDiff', models.FloatField(blank=True, db_column='PerDiff', null=True)),
                ('Duration', models.FloatField(blank=True, db_column='Duration', null=True)),
            ],
            options={
                'db_table': 'vizpoc',
                'managed': True,
                'unique_together': {('UtilityName', 'StateName', 'CountyName', 'RecordDateTime')},
            },
        ),
    ]
