# Generated by Django 2.2.1 on 2019-06-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querybuilderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eod_hd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_column='Date')),
                ('Open', models.FloatField(db_column='Open')),
                ('High', models.FloatField(db_column='High')),
                ('Low', models.FloatField(db_column='Low')),
                ('Close', models.FloatField(db_column='Close')),
                ('Volume', models.FloatField(db_column='Volume')),
                ('Dividend', models.FloatField(db_column='Dividend')),
                ('Split', models.FloatField(db_column='Split')),
                ('AdjOpen', models.FloatField(db_column='AdjOpen')),
                ('AdjHigh', models.FloatField(db_column='AdjHigh')),
                ('AdjLow', models.FloatField(db_column='AdjLow')),
                ('AdjClose', models.FloatField(db_column='AdjClose')),
                ('AdjVolume', models.FloatField(db_column='AdjVolume')),
            ],
            options={
                'db_table': 'eod_hd',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='vizpoc',
        ),
    ]
