# Generated by Django 2.2.1 on 2019-06-02 15:29

from django.db import migrations
import querybuilderapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('querybuilderapp', '0002_auto_20190602_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eod_hd',
            name='Date',
            field=querybuilderapp.utils.MyModelDateField(db_column='Date'),
        ),
    ]
